// Generated by https://quicktype.io

export interface GetProduct {
  _id: string;
  name: string;
  description: string;
  sku: string;
  imageUrl: string;
  tags: string[];
  price: number;
  stock: number;
  priceHistory: PriceHistory[];
  stockHistory: StockHistory[];
  createdAt: string;
  updatedAt: string;
  __v: number;
}

export interface PriceHistory {
  date: string;
  price: number;
  _id: string;
}

export interface StockHistory {
  date: string;
  stock: number;
  _id: string;
}
